"""Initial metastore schema: 13 tables plus immutability triggers.

Autogenerated from evalloop/store/models.py, then extended by hand with the
UPDATE/DELETE guards on snapshot and feedback_dataset. Those are Postgres-only;
unit tests build the schema from metadata on SQLite and skip them.

Revision ID: 0001
Revises:
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "comparison",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("baseline_model", sa.String(length=255), nullable=False),
        sa.Column("candidate_model", sa.String(length=255), nullable=False),
        sa.Column(
            "run_ids",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "gate_result",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=False,
        ),
        sa.Column("decision", sa.String(length=16), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("decision IN ('promote', 'reject')", name="ck_comparison_decision"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "judge_config",
        sa.Column("hash", sa.String(length=64), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("model", sa.String(length=255), nullable=False),
        sa.Column(
            "params",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=False,
        ),
        sa.Column("system_prompt", sa.Text(), nullable=True),
        sa.Column(
            "rubric",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=True,
        ),
        sa.Column(
            "response_schema",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("hash"),
    )
    op.create_table(
        "llm_cache",
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("judge_config_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "response",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "usage",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_index("ix_llm_cache_created_at", "llm_cache", ["created_at"], unique=False)
    op.create_table(
        "project",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("config_yaml", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "snapshot",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("project_id", sa.String(length=64), nullable=False),
        sa.Column("source_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("row_count", sa.Integer(), nullable=False),
        sa.Column(
            "redaction_report",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=True,
        ),
        sa.Column(
            "split_report",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("row_count >= 0", name="ck_snapshot_row_count"),
        sa.ForeignKeyConstraint(["project_id"], ["project.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_fingerprint"),
    )
    op.create_table(
        "eval_run",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("snapshot_id", sa.String(length=64), nullable=False),
        sa.Column("suite_hash", sa.String(length=64), nullable=False),
        sa.Column("split", sa.String(length=16), nullable=False),
        sa.Column("model_name", sa.String(length=255), nullable=True),
        sa.Column("status", sa.String(length=16), server_default="running", nullable=False),
        sa.Column("cost_usd", sa.Float(), server_default=sa.text("0"), nullable=False),
        sa.Column("tokens_in", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("tokens_out", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("cache_hits", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("split IN ('train', 'dev', 'test')", name="ck_eval_run_split"),
        sa.CheckConstraint(
            "status IN ('running', 'completed', 'failed', 'partial')", name="ck_eval_run_status"
        ),
        sa.ForeignKeyConstraint(["snapshot_id"], ["snapshot.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_eval_run_snapshot", "eval_run", ["snapshot_id", "split"], unique=False)
    op.create_table(
        "split_assignment",
        sa.Column("snapshot_id", sa.String(length=64), nullable=False),
        sa.Column("trace_id", sa.String(length=255), nullable=False),
        sa.Column("split", sa.String(length=16), nullable=False),
        sa.Column("split_key", sa.String(length=255), nullable=True),
        sa.Column("split_strategy", sa.String(length=32), nullable=False),
        sa.Column("sealed", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.CheckConstraint("split IN ('train', 'dev', 'test')", name="ck_split_assignment_split"),
        sa.ForeignKeyConstraint(["snapshot_id"], ["snapshot.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("snapshot_id", "trace_id"),
        sa.UniqueConstraint("snapshot_id", "trace_id", name="uq_split_assignment_trace"),
    )
    op.create_table(
        "trace",
        sa.Column("snapshot_id", sa.String(length=64), nullable=False),
        sa.Column("trace_id", sa.String(length=255), nullable=False),
        sa.Column("split", sa.String(length=16), server_default="train", nullable=False),
        sa.Column("parquet_path", sa.Text(), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.CheckConstraint("split IN ('train', 'dev', 'test')", name="ck_trace_split"),
        sa.ForeignKeyConstraint(["snapshot_id"], ["snapshot.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("snapshot_id", "trace_id"),
    )
    op.create_index("ix_trace_content_hash", "trace", ["content_hash"], unique=False)
    op.create_index("ix_trace_snapshot_split", "trace", ["snapshot_id", "split"], unique=False)
    op.create_table(
        "eval_result",
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column("trace_id", sa.String(length=255), nullable=False),
        sa.Column("evaluator_id", sa.String(length=255), nullable=False),
        sa.Column("evaluator_version", sa.String(length=64), nullable=False),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column("passed", sa.Boolean(), nullable=True),
        sa.Column(
            "normalized_prediction",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=True,
        ),
        sa.Column(
            "ground_truth",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=True,
        ),
        sa.Column("explanation", sa.Text(), nullable=True),
        sa.Column(
            "raw_output",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=True,
        ),
        sa.Column("judge_config_hash", sa.String(length=64), nullable=True),
        sa.Column("cache_hit", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("invalid_output", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("cost_usd", sa.Float(), nullable=True),
        sa.Column("tokens_in", sa.Integer(), nullable=True),
        sa.Column("tokens_out", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["judge_config_hash"], ["judge_config.hash"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["run_id"], ["eval_run.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("run_id", "trace_id", "evaluator_id"),
    )
    op.create_index(
        "ix_eval_result_run_evaluator", "eval_result", ["run_id", "evaluator_id"], unique=False
    )
    op.create_index("ix_eval_result_run_trace", "eval_result", ["run_id", "trace_id"], unique=False)
    op.create_table(
        "feedback_dataset",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column("strategy", sa.String(length=16), nullable=False),
        sa.Column(
            "manifest",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=False,
        ),
        sa.Column("path", sa.Text(), nullable=False),
        sa.Column("row_count", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("strategy IN ('sft', 'dpo')", name="ck_feedback_dataset_strategy"),
        sa.CheckConstraint("row_count >= 0", name="ck_feedback_dataset_row_count"),
        sa.ForeignKeyConstraint(["run_id"], ["eval_run.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "judgecard",
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column("evaluator_id", sa.String(length=255), nullable=False),
        sa.Column(
            "metrics",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "health",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=True,
        ),
        sa.Column(
            "eligible_for_feedback", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["run_id"], ["eval_run.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("run_id", "evaluator_id"),
    )
    op.create_table(
        "train_run",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("dataset_id", sa.String(length=64), nullable=False),
        sa.Column("backend", sa.String(length=32), nullable=False),
        sa.Column("base_model", sa.String(length=255), nullable=False),
        sa.Column("base_provider", sa.String(length=64), nullable=True),
        sa.Column(
            "config",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "manifest",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=True,
        ),
        sa.Column("status", sa.String(length=16), server_default="pending", nullable=False),
        sa.Column("artifact_uri", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'running', 'completed', 'failed')", name="ck_train_run_status"
        ),
        sa.ForeignKeyConstraint(["dataset_id"], ["feedback_dataset.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "model_registry",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("train_run_id", sa.String(length=64), nullable=True),
        sa.Column(
            "endpoint_conf",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=False,
        ),
        sa.Column("promoted", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("kind IN ('baseline', 'candidate')", name="ck_model_registry_kind"),
        sa.ForeignKeyConstraint(["train_run_id"], ["train_run.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    # ### end Alembic commands ###

    # --- immutability, enforced by the database rather than by convention ---
    #
    # snapshot and feedback_dataset are cited as evidence by everything
    # downstream. A judgecard from three months ago only means what it said if
    # nothing could have edited the snapshot underneath it, and a training run
    # can only name which rows it saw if its dataset row cannot be rewritten.
    # An application-level check is bypassed by the next person with psql open.
    op.execute(
        """
        CREATE OR REPLACE FUNCTION evalloop_forbid_mutation()
        RETURNS TRIGGER AS $$
        BEGIN
            RAISE EXCEPTION
                'table % is immutable: % is not permitted. Create a new row instead.',
                TG_TABLE_NAME, TG_OP
                USING ERRCODE = 'restrict_violation';
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    for table in ("snapshot", "feedback_dataset"):
        op.execute(
            f"""
            CREATE TRIGGER {table}_immutable
            BEFORE UPDATE OR DELETE ON {table}
            FOR EACH ROW EXECUTE FUNCTION evalloop_forbid_mutation();
            """
        )


def downgrade() -> None:
    # Triggers first: their own tables cannot be dropped while they guard them.
    for table in ("snapshot", "feedback_dataset"):
        op.execute(f"DROP TRIGGER IF EXISTS {table}_immutable ON {table};")
    op.execute("DROP FUNCTION IF EXISTS evalloop_forbid_mutation();")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("model_registry")
    op.drop_table("train_run")
    op.drop_table("judgecard")
    op.drop_table("feedback_dataset")
    op.drop_index("ix_eval_result_run_trace", table_name="eval_result")
    op.drop_index("ix_eval_result_run_evaluator", table_name="eval_result")
    op.drop_table("eval_result")
    op.drop_index("ix_trace_snapshot_split", table_name="trace")
    op.drop_index("ix_trace_content_hash", table_name="trace")
    op.drop_table("trace")
    op.drop_table("split_assignment")
    op.drop_index("ix_eval_run_snapshot", table_name="eval_run")
    op.drop_table("eval_run")
    op.drop_table("snapshot")
    op.drop_table("project")
    op.drop_index("ix_llm_cache_created_at", table_name="llm_cache")
    op.drop_table("llm_cache")
    op.drop_table("judge_config")
    op.drop_table("comparison")
    # ### end Alembic commands ###
